# Generated by Django 5.2.4 on 2025-07-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shared", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_contract",
                    models.CharField(help_text="Objeto do Contrato", max_length=255),
                ),
                (
                    "executed_activities",
                    models.TextField(help_text="Atividades Executadas"),
                ),
                (
                    "contract_start_date",
                    models.DateField(help_text="Data de Início do Contrato"),
                ),
                (
                    "contract_end_date",
                    models.DateField(help_text="Data Final do Contrato"),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "db_table": "contract",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomBusinessSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Business Sector",
                "verbose_name_plural": "Business Sectors",
                "db_table": "business_sector",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "category",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Classification",
                "verbose_name_plural": "Classifications",
                "db_table": "classification",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomCompanySize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Company Size",
                "verbose_name_plural": "Company Sizes",
                "db_table": "company_size",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomCustomerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Customer Type",
                "verbose_name_plural": "Customer Types",
                "db_table": "customer_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomIcmsTaxpayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "ICMS Taxpayer",
                "verbose_name_plural": "ICMS Taxpayers",
                "db_table": "icms_taxpayer",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomIncomeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Income Type",
                "verbose_name_plural": "Income Types",
                "db_table": "income_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomIssRegime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "ISS Regime",
                "verbose_name_plural": "ISS Regimes",
                "db_table": "iss_regime",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomIssWithholding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "ISS Withholding",
                "verbose_name_plural": "ISS Withholdings",
                "db_table": "iss_withholding",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomPayerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Payer Type",
                "verbose_name_plural": "Payer Types",
                "db_table": "payer_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "payment_method",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomPixType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Pix Type",
                "verbose_name_plural": "Pix Types",
                "db_table": "pix_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomPublicEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Public Entity",
                "verbose_name_plural": "Public Entities",
                "db_table": "public_entity",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomRiskLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Risk Level",
                "verbose_name_plural": "Risk Levels",
                "db_table": "risk_level",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomSupplierSituation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Supplier Situation",
                "verbose_name_plural": "Supplier Situations",
                "db_table": "supplier_situation",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomTaxationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Taxation Method",
                "verbose_name_plural": "Taxation Methods",
                "db_table": "taxation_method",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomTaxpayerClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Taxpayer Classification",
                "verbose_name_plural": "Taxpayer Classifications",
                "db_table": "taxpayer_classification",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomTypeSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Type Supplier",
                "verbose_name_plural": "Type Suppliers",
                "db_table": "type_supplier",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomWithholdingTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Withholding Tax",
                "verbose_name_plural": "Withholding Taxes",
                "db_table": "withholding_tax",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "taxation_regime",
                    models.CharField(help_text="Regime de Tributação", max_length=100),
                ),
                (
                    "revenue_code",
                    models.CharField(help_text="Código da Receita", max_length=20),
                ),
                (
                    "nit",
                    models.CharField(
                        blank=True,
                        help_text="NIT (Número de Identificação do Trabalhador)",
                        max_length=20,
                    ),
                ),
                (
                    "company_size",
                    models.ForeignKey(
                        help_text="Porte da Empresa",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="company_information",
                        to="supplier.domcompanysize",
                    ),
                ),
                (
                    "customer_type",
                    models.ForeignKey(
                        help_text="Tipo de Cliente",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="company_information",
                        to="supplier.domcustomertype",
                    ),
                ),
                (
                    "icms_taxpayer",
                    models.ForeignKey(
                        help_text="Contribuinte ICMS",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="company_information",
                        to="supplier.domicmstaxpayer",
                    ),
                ),
                (
                    "income_type",
                    models.ForeignKey(
                        help_text="Tipo de Rendimento",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="company_information",
                        to="supplier.domincometype",
                    ),
                ),
                (
                    "taxation_method",
                    models.ForeignKey(
                        help_text="Forma de Tributação",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="company_information",
                        to="supplier.domtaxationmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informações da Empresa",
                "verbose_name_plural": "Informações da Empresa",
                "db_table": "company_information",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiscalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "iss_taxpayer",
                    models.BooleanField(default=False, help_text="Contribuinte ISS"),
                ),
                (
                    "simples_nacional_participant",
                    models.BooleanField(
                        default=False, help_text="Optante pelo Simples Nacional"
                    ),
                ),
                (
                    "cooperative_member",
                    models.BooleanField(default=False, help_text="Sócio Cooperado"),
                ),
                (
                    "iss_regime",
                    models.ForeignKey(
                        help_text="Regime ISS",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fiscal_details",
                        to="supplier.domissregime",
                    ),
                ),
                (
                    "iss_withholding",
                    models.ForeignKey(
                        help_text="Retenção de ISS",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fiscal_details",
                        to="supplier.domisswithholding",
                    ),
                ),
                (
                    "withholding_tax_nature",
                    models.ForeignKey(
                        help_text="Natureza da Retenção na Fonte",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fiscal_details",
                        to="supplier.domwithholdingtax",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhes Fiscais",
                "verbose_name_plural": "Detalhes Fiscais",
                "db_table": "fiscal_details",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_center",
                    models.CharField(help_text="Centro de Custo", max_length=50),
                ),
                (
                    "business_unit",
                    models.CharField(
                        help_text="BU (Unidade de Negócio)", max_length=100
                    ),
                ),
                (
                    "responsible_executive",
                    models.CharField(help_text="Executivo Responsável", max_length=255),
                ),
                (
                    "business_sector",
                    models.ForeignKey(
                        help_text="Ramo de Atividade",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organizational_details",
                        to="supplier.dombusinesssector",
                    ),
                ),
                (
                    "payer_type",
                    models.ForeignKey(
                        help_text="Tipo de Tomador",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organizational_details",
                        to="supplier.dompayertype",
                    ),
                ),
                (
                    "public_entity",
                    models.ForeignKey(
                        help_text="Órgão Público",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organizational_details",
                        to="supplier.dompublicentity",
                    ),
                ),
                (
                    "taxpayer_classification",
                    models.ForeignKey(
                        help_text="Classificação do Contribuinte",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="organizational_details",
                        to="supplier.domtaxpayerclassification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhes Organizacionais",
                "verbose_name_plural": "Detalhes Organizacionais",
                "db_table": "organizational_details",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_frequency",
                    models.CharField(
                        help_text="Periodicidade do Pagamento", max_length=50
                    ),
                ),
                ("payment_date", models.DateField(help_text="Data de Pagamento")),
                (
                    "contract_total_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor Total do Contrato",
                        max_digits=15,
                    ),
                ),
                (
                    "contract_monthly_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor Mensal do Contrato",
                        max_digits=15,
                    ),
                ),
                (
                    "checking_account",
                    models.CharField(help_text="Conta Corrente", max_length=20),
                ),
                ("pix_key", models.CharField(help_text="Chave PIX", max_length=255)),
                (
                    "payment_method",
                    models.ForeignKey(
                        help_text="Forma de Pagamento",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payment_details",
                        to="supplier.dompaymentmethod",
                    ),
                ),
                (
                    "pix_key_type",
                    models.ForeignKey(
                        help_text="Tipo de Chave PIX",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payment_details",
                        to="supplier.dompixtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhes de Pagamento",
                "verbose_name_plural": "Detalhes de Pagamento",
                "db_table": "payment_details",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade_name",
                    models.CharField(help_text="Nome fantasia", max_length=255),
                ),
                (
                    "legal_name",
                    models.CharField(
                        help_text="Razão Social", max_length=255, unique=True
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(help_text="CPF/CNPJ", max_length=16, unique=True),
                ),
                (
                    "state_business_registration",
                    models.CharField(help_text="Inscrição Estadual", max_length=20),
                ),
                (
                    "municipal_business_registration",
                    models.CharField(help_text="Inscrição Municipal", max_length=20),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier",
                        to="shared.address",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="suppliers",
                        to="supplier.domcategory",
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="suppliers",
                        to="supplier.domclassification",
                    ),
                ),
                (
                    "company_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier",
                        to="supplier.companyinformation",
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier",
                        to="shared.contact",
                    ),
                ),
                (
                    "fiscal_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier",
                        to="supplier.fiscaldetails",
                    ),
                ),
                (
                    "organizational_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier",
                        to="supplier.organizationaldetails",
                    ),
                ),
                (
                    "payment_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier",
                        to="supplier.paymentdetails",
                    ),
                ),
                (
                    "risk_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="suppliers",
                        to="supplier.domrisklevel",
                    ),
                ),
                (
                    "situation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="suppliers",
                        to="supplier.domsuppliersituation",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="suppliers",
                        to="supplier.domtypesupplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "supplier",
                "abstract": False,
            },
        ),
    ]
