# Generated by Django 5.2.4 on 2025-07-20 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomTaxationRegime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Taxation Regime",
                "verbose_name_plural": "Taxation Regimes",
                "db_table": "taxation_regime",
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="companyinformation",
            name="revenue_code",
        ),
        migrations.AlterField(
            model_name="companyinformation",
            name="taxation_regime",
            field=models.ForeignKey(
                help_text="Regime de Tributação",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_information",
                to="supplier.domtaxationregime",
            ),
        ),
    ]
