# Generated by Django 5.2.4 on 2025-07-23 02:17

import django.db.models.deletion
from django.db import migrations, models

import src.supplier.models.attachments


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0002_domtaxationregime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomAttachmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Attachment Type",
                "verbose_name_plural": "Attachment Types",
                "db_table": "attachment_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Arquivo do Anexo",
                        upload_to=src.supplier.models.attachments.supplier_attachment_upload_path,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição do Anexo", null=True
                    ),
                ),
                (
                    "attachment_type",
                    models.ForeignKey(
                        help_text="Tipo de Anexo",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="attachments",
                        to="supplier.domattachmenttype",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Fornecedor relacionado ao anexo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="supplier.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Attachment",
                "verbose_name_plural": "Supplier Attachments",
                "db_table": "supplier_attachment",
                "abstract": False,
            },
        ),
    ]
