# Generated by Django 5.2.4 on 2025-07-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0004_responsibilitymatrix"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="contract",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier",
                to="supplier.contract",
            ),
            preserve_default=False,
        ),
    ]
