# Generated by Django 5.2.4 on 2025-07-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0005_supplier_contract"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplierattachment",
            unique_together={("supplier", "attachment_type")},
        ),
        migrations.DeleteModel(
            name="ResponsibilityMatrix",
        ),
    ]
