# Generated by Django 5.2.4 on 2025-07-31 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0007_responsibilitymatrix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domattachmenttype",
            options={
                "verbose_name": "Tipo de Anexo",
                "verbose_name_plural": "Tipos de Anexo",
            },
        ),
        migrations.AlterModelOptions(
            name="dombusinesssector",
            options={
                "verbose_name": "Ramo de Atividade",
                "verbose_name_plural": "Ramos de Atividade",
            },
        ),
        migrations.AlterModelOptions(
            name="domcategory",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="domclassification",
            options={
                "verbose_name": "Classificação",
                "verbose_name_plural": "Classificações",
            },
        ),
        migrations.AlterModelOptions(
            name="domcompanysize",
            options={
                "verbose_name": "Tamanho da Empresa",
                "verbose_name_plural": "Tamanhos de Empresa",
            },
        ),
        migrations.AlterModelOptions(
            name="domcustomertype",
            options={
                "verbose_name": "Tipo de Cliente",
                "verbose_name_plural": "Tipos de Cliente",
            },
        ),
        migrations.AlterModelOptions(
            name="domicmstaxpayer",
            options={
                "verbose_name": "Contribuinte ICMS",
                "verbose_name_plural": "Contribuintes ICMS",
            },
        ),
        migrations.AlterModelOptions(
            name="domincometype",
            options={
                "verbose_name": "Tipo de Rendimento",
                "verbose_name_plural": "Tipos de Rendimento",
            },
        ),
        migrations.AlterModelOptions(
            name="domissregime",
            options={
                "verbose_name": "Regime ISS",
                "verbose_name_plural": "Regimes ISS",
            },
        ),
        migrations.AlterModelOptions(
            name="domisswithholding",
            options={
                "verbose_name": "ISS Retenção",
                "verbose_name_plural": "ISS Retenções",
            },
        ),
        migrations.AlterModelOptions(
            name="dompayertype",
            options={
                "verbose_name": "Tipo de Pagador",
                "verbose_name_plural": "Tipos de Pagador",
            },
        ),
        migrations.AlterModelOptions(
            name="dompaymentmethod",
            options={
                "verbose_name": "Método de Pagamento",
                "verbose_name_plural": "Métodos de Pagamento",
            },
        ),
        migrations.AlterModelOptions(
            name="dompixtype",
            options={
                "verbose_name": "Tipo de Pix",
                "verbose_name_plural": "Tipos de Pix",
            },
        ),
        migrations.AlterModelOptions(
            name="dompublicentity",
            options={
                "verbose_name": "Entidade Pública",
                "verbose_name_plural": "Entidades Públicas",
            },
        ),
        migrations.AlterModelOptions(
            name="domrisklevel",
            options={
                "verbose_name": "Grau de Risco",
                "verbose_name_plural": "Grau de Risco",
            },
        ),
        migrations.AlterModelOptions(
            name="domsuppliersituation",
            options={
                "verbose_name": "Situação do Fornecedor",
                "verbose_name_plural": "Situações do Fornecedor",
            },
        ),
        migrations.AlterModelOptions(
            name="domtaxationmethod",
            options={
                "verbose_name": "Método de Tributação",
                "verbose_name_plural": "Métodos de Tributação",
            },
        ),
        migrations.AlterModelOptions(
            name="domtaxationregime",
            options={
                "verbose_name": "Regime de Tributação",
                "verbose_name_plural": "Regimes de Tributação",
            },
        ),
        migrations.AlterModelOptions(
            name="domtaxpayerclassification",
            options={
                "verbose_name": "Classificação de Contribuinte",
                "verbose_name_plural": "Classificações de Contribuintes",
            },
        ),
        migrations.AlterModelOptions(
            name="domtypesupplier",
            options={
                "verbose_name": "Tipo de Fornecedor",
                "verbose_name_plural": "Tipos de Fornecedor",
            },
        ),
        migrations.AlterModelOptions(
            name="domwithholdingtax",
            options={
                "verbose_name": "Imposto Retido",
                "verbose_name_plural": "Impostos Retidos",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
        migrations.AlterModelOptions(
            name="supplierattachment",
            options={
                "verbose_name": "Anexo de Fornecedor",
                "verbose_name_plural": "Anexos de Fornecedor",
            },
        ),
    ]
