# Generated by Django 5.2.4 on 2025-08-01 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0008_alter_domattachmenttype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domattachmenttype",
            name="risk_level",
            field=models.ForeignKey(
                help_text="Nível de Risco associado ao tipo de anexo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment_types",
                to="supplier.domrisklevel",
            ),
        ),
    ]
