# Generated by Django 5.2.4 on 2025-08-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0009_domattachmenttype_risk_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domattachmenttype",
            name="name",
            field=models.CharField(help_text="Nome do tipo de anexo", max_length=255),
        ),
    ]
