# Generated by Django 5.2.4 on 2025-08-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0010_alter_domattachmenttype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetails",
            name="agency",
            field=models.CharField(
                blank=True, default="", help_text="Agência", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="paymentdetails",
            name="bank",
            field=models.CharField(
                blank=True, default="", help_text="Banco", max_length=50
            ),
        ),
    ]
