# Generated by Django 5.2.4 on 2025-08-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0011_paymentdetails_agency_paymentdetails_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsibilitymatrix",
            name="contract_execution_monitoring_administrative",
            field=models.CharField(
                choices=[
                    ("A", "A - Accountable (Responsável)"),
                    ("R", "R - Responsible (Executa)"),
                    ("C", "C - Consulted (Consultado)"),
                    ("I", "I - Informed (Informado)"),
                    ("-", "- Não Envolvido"),
                    ("A/R", "A/R - Responsável e Executa"),
                ],
                default="-",
                help_text="Administrativo / Cadastro",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="responsibilitymatrix",
            name="contract_execution_monitoring_board",
            field=models.CharField(
                choices=[
                    ("A", "A - Accountable (Responsável)"),
                    ("R", "R - Responsible (Executa)"),
                    ("C", "C - Consulted (Consultado)"),
                    ("I", "I - Informed (Informado)"),
                    ("-", "- Não Envolvido"),
                    ("A/R", "A/R - Responsável e Executa"),
                ],
                default="-",
                help_text="Diretoria / Gestão",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="responsibilitymatrix",
            name="contract_execution_monitoring_financial",
            field=models.CharField(
                choices=[
                    ("A", "A - Accountable (Responsável)"),
                    ("R", "R - Responsible (Executa)"),
                    ("C", "C - Consulted (Consultado)"),
                    ("I", "I - Informed (Informado)"),
                    ("-", "- Não Envolvido"),
                    ("A/R", "A/R - Responsável e Executa"),
                ],
                default="-",
                help_text="Financeiro",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="responsibilitymatrix",
            name="contract_execution_monitoring_integrity",
            field=models.CharField(
                choices=[
                    ("A", "A - Accountable (Responsável)"),
                    ("R", "R - Responsible (Executa)"),
                    ("C", "C - Consulted (Consultado)"),
                    ("I", "I - Informed (Informado)"),
                    ("-", "- Não Envolvido"),
                    ("A/R", "A/R - Responsável e Executa"),
                ],
                default="-",
                help_text="Integridade / Compliance",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="responsibilitymatrix",
            name="contract_execution_monitoring_legal",
            field=models.CharField(
                choices=[
                    ("A", "A - Accountable (Responsável)"),
                    ("R", "R - Responsible (Executa)"),
                    ("C", "C - Consulted (Consultado)"),
                    ("I", "I - Informed (Informado)"),
                    ("-", "- Não Envolvido"),
                    ("A/R", "A/R - Responsável e Executa"),
                ],
                default="-",
                help_text="Jurídico",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="responsibilitymatrix",
            name="contract_execution_monitoring_requesting_area",
            field=models.CharField(
                choices=[
                    ("A", "A - Accountable (Responsável)"),
                    ("R", "R - Responsible (Executa)"),
                    ("C", "C - Consulted (Consultado)"),
                    ("I", "I - Informed (Informado)"),
                    ("-", "- Não Envolvido"),
                    ("A/R", "A/R - Responsável e Executa"),
                ],
                default="-",
                help_text="Área Solicitante",
                max_length=3,
            ),
        ),
    ]
