# Generated by Django 5.2.4 on 2025-08-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0013_optional_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_period",
            field=models.CharField(
                blank=True, default="", help_text="Período do Contrato", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_type",
            field=models.CharField(
                blank=True, default="", help_text="Tipo de Contrato", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="has_contract_renewal",
            field=models.BooleanField(default=False, help_text="Renovação de Contrato"),
        ),
        migrations.AddField(
            model_name="contract",
            name="warning_contract_period",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Aviso Prévio de Contrato",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="warning_contract_renewal",
            field=models.BooleanField(
                default=False, help_text="Aviso de Renovação de Contrato"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="warning_on_period",
            field=models.BooleanField(
                default=False, help_text="Tem Aviso Prévio de Contrato"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="warning_on_renewal",
            field=models.BooleanField(
                default=False, help_text="Tem Aviso de Renovação de Contrato"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="warning_on_termination",
            field=models.BooleanField(
                default=False, help_text="Tem Aviso de Término de Contrato"
            ),
        ),
    ]
