# Generated by Django 5.2.4 on 2025-08-12 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0014_contract_contract_period_contract_contract_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomPendecyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Pendência",
                "verbose_name_plural": "Tipos de Pendência",
                "db_table": "pendecy_type",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="domsuppliersituation",
            name="pendency_type",
            field=models.ForeignKey(
                help_text="Tipo de Pendência",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="supplier_situation",
                to="supplier.dompendecytype",
            ),
        ),
    ]
