# Generated by Django 5.2.4 on 2025-08-16 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0015_dompendecytype_domsuppliersituation_pendency_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="domsuppliersituation",
            unique_together={("name", "pendency_type")},
        ),
    ]
