# Generated by Django 5.2.4 on 2025-08-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0016_alter_domsuppliersituation_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domsuppliersituation",
            name="name",
            field=models.CharField(
                help_text="Nome da Situação do Fornecedor",
                max_length=255,
                verbose_name="Nome",
            ),
        ),
    ]
