# Generated by Django 5.2.4 on 2025-08-27 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0017_alter_domsuppliersituation_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="situation",
        ),
        migrations.AlterModelTable(
            name="domsuppliersituation",
            table="supplier_situation_type",
        ),
        migrations.CreateModel(
            name="SupplierSituation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situations",
                        to="supplier.domsuppliersituation",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situation",
                        to="supplier.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Situação do Fornecedor",
                "verbose_name_plural": "Situações do Fornecedor",
                "db_table": "supplier_situation",
                "abstract": False,
                "unique_together": {("supplier", "status")},
            },
        ),
    ]
