# Generated by Django 5.2.4 on 2025-08-27 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0018_remove_supplier_situation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliersituation",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="situations",
                to="supplier.supplier",
            ),
        ),
    ]
