# Generated by Django 5.2.4 on 2025-08-31 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0020_evaluationcriterion_evaluationperiod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsibilitymatrix",
            name="supplier",
            field=models.OneToOneField(
                help_text="Fornecedor vinculado à matriz",
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier.supplier",
            ),
        ),
    ]
