# Generated by Django 5.2.4 on 2025-09-12 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0022_alter_responsibilitymatrix_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierattachment",
            name="attachment_type",
            field=models.ForeignKey(
                help_text="Tipo de Anexo",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="supplier.domattachmenttype",
            ),
        ),
    ]
