# Generated by Django 5.2.4 on 2025-09-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0024_alter_supplierattachment_attachment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="tax_id",
            field=models.CharField(help_text="CPF/CNPJ", max_length=18, unique=True),
        ),
    ]
