# Generated by Django 5.2.4 on 2025-09-15 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0025_alter_supplier_tax_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DomPendecyType",
            new_name="DomPendencyType",
        ),
    ]
