# Generated by Django 5.2.4 on 2025-09-26 01:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0026_rename_dompendecytype_dompendencytype"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Passo"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Ordem de execução do passo no fluxo",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Departamento responsável por este passo",
                        max_length=100,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se este passo é obrigatório no fluxo de aprovação",
                        verbose_name="Obrigatório",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passo de Aprovação",
                "verbose_name_plural": "Passos de Aprovação",
                "db_table": "approval_step",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data de início do fluxo de aprovação",
                        verbose_name="Data de Início",
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de conclusão do fluxo de aprovação",
                        null=True,
                        verbose_name="Data de Conclusão",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_flow",
                        to="supplier.supplier",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="Passo atual no fluxo de aprovação",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_flows",
                        to="supplier.approvalstep",
                        verbose_name="Passo Atual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fluxo de Aprovação",
                "verbose_name_plural": "Fluxos de Aprovação",
                "db_table": "approval_flow",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StepApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver_name",
                    models.CharField(max_length=255, verbose_name="Nome do Aprovador"),
                ),
                (
                    "approver_department",
                    models.CharField(
                        max_length=100, verbose_name="Departamento do Aprovador"
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Aprovação",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o passo foi aprovado ou rejeitado",
                        verbose_name="Aprovado",
                    ),
                ),
                (
                    "approval_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_approvals",
                        to="supplier.approvalflow",
                        verbose_name="Fluxo de Aprovação",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="supplier.approvalstep",
                        verbose_name="Passo de Aprovação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aprovação de Passo",
                "verbose_name_plural": "Aprovações de Passos",
                "db_table": "step_approval",
                "ordering": ["approval_flow", "step__order"],
                "abstract": False,
                "unique_together": {("approval_flow", "step")},
            },
        ),
    ]
