# Generated by Django 5.2.4 on 2025-10-05 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0026_rename_dompendecytype_dompendencytype"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Passo"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Ordem de execução do passo no fluxo",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Departamento responsável por este passo",
                        max_length=100,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se este passo é obrigatório no fluxo de aprovação",
                        verbose_name="Obrigatório",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passo de Aprovação",
                "verbose_name_plural": "Passos de Aprovação",
                "db_table": "approval_step",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Approver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nome completo do aprovador",
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email do aprovador",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aprovador",
                "verbose_name_plural": "Aprovadores",
                "db_table": "approver",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data em que o fluxo foi aprovado",
                        null=True,
                        verbose_name="Data de Aprovação",
                    ),
                ),
                (
                    "reproved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data em que o fluxo foi reprovado",
                        null=True,
                        verbose_name="Data de Reprovação",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_flow_history",
                        to="supplier.supplier",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="Passo atual no fluxo de aprovação",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_flows",
                        to="supplier.approvalstep",
                        verbose_name="Passo Atual",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aprovador responsável pelo passo atual",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_flows",
                        to="supplier.approver",
                        verbose_name="Aprovador Atual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fluxo de Aprovação",
                "verbose_name_plural": "Fluxos de Aprovação",
                "db_table": "approval_flow",
                "abstract": False,
            },
        ),
    ]
