# Generated by Django 5.2.4 on 2025-11-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0027_approvalstep_approver_approvalflow"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="dompendencytype",
            table="pendency_type",
        ),
    ]
