# Generated by Django 5.2.4 on 2025-11-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0028_alter_dompendencytype_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetails",
            name="payment_date",
            field=models.CharField(
                blank=True, default="", help_text="Data de Pagamento", max_length=100
            ),
        ),
    ]
