# Generated by Django 5.2.4 on 2025-11-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0029_alter_paymentdetails_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalflow",
            name="observations",
            field=models.TextField(
                blank=True,
                help_text="Observações adicionais sobre o fluxo de aprovação",
                verbose_name="Observações",
            ),
        ),
    ]
