# Generated by Django 5.2.4 on 2026-01-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0030_approvalflow_observations"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetails",
            name="bank_code",
            field=models.CharField(
                blank=True, default="", help_text="Código do Banco", max_length=50
            ),
        ),
    ]
