# Generated by Django 5.2.4 on 2026-01-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0031_paymentdetails_bank_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_period",
            field=models.CharField(
                blank=True, default="", help_text="Período do Contrato", max_length=50
            ),
        ),
    ]
