# Generated by Django 5.2.4 on 2026-04-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0032_alter_contract_contract_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationaldetails",
            name="responsible_manager",
            field=models.CharField(
                blank=True, default="", help_text="Gestor Responsável", max_length=255
            ),
        ),
    ]
