# Generated by Django 5.2.4 on 2026-04-12 00:00

import django.db.models.deletion
from django.db import migrations, models

import src.utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0032_alter_contract_contract_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierAttachmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Arquivo do Anexo",
                        upload_to=src.utils.upload.supplier_attachment_upload_path,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descricao do Anexo",
                    ),
                ),
                (
                    "attachment_type",
                    models.ForeignKey(
                        help_text="Tipo de Anexo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachment_history",
                        to="supplier.domattachmenttype",
                    ),
                ),
                (
                    "source_attachment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Anexo atual que originou esta versao",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_entries",
                        to="supplier.supplierattachment",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Fornecedor relacionado ao anexo historico",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_history",
                        to="supplier.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historico de Anexo de Fornecedor",
                "verbose_name_plural": "Historicos de Anexo de Fornecedor",
                "db_table": "supplier_attachment_history",
                "abstract": False,
            },
        ),
    ]
