# Generated by Django 5.2.4 on 2026-04-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0033_organizationaldetails_responsible_manager"),
        ("supplier", "0033_supplierattachmenthistory"),
    ]

    operations = []
