# Generated by Django 5.2.4 on 2025-07-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_alter_address_postal_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Endereço", "verbose_name_plural": "Endereços"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contato", "verbose_name_plural": "Contatos"},
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
