# Generated by Django 5.2.4 on 2025-08-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0003_alter_address_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
