# Generated by Django 5.2.4 on 2025-09-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0004_alter_address_city_alter_address_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
