# Generated by Django 5.2.4 on 2025-11-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0005_alter_address_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
